### ISSUE TITLE
  #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

### ISSUE THREAD

**Issue by 5calV** [cyijun/ESP32MQTTClient#11]
When trying to compile it for an ESP32-WROOM-32, I get following error:

 #error "This library only supports boards with an AVR, SAM, SAMD, NRF52 or STM32F4 processor."

I thought this lib is for the ESP32?

**Comment by cyijun** [comment]
Hi, would you please paste more context about this error? I have never seen this before🤔
