### ISSUE TITLE
Keinerlei Funktion

### ISSUE THREAD

**Issue by elzershark** [cyijun/ESP32MQTTClient#2]
Keinerlei Funktion
Egal was man für eine ip eingibt, es funktioniert nicht.
MQTT_CLIENT: There are no transports valid, stop mqtt client, config scheme = http

**Comment by cyijun** [comment]
hi elzer, would you please paste your code here?

**Comment by elzershark** [comment]
ou.. i down't know. That was too long ago. I solved it differently. Just test it yourself. Then you see for yourself that it doesn't work.
